const data = [
  {
    name: "ABHINAV JAYALWAAL",
    rollno: "22UCSE4001",
    password: "Abhinav@4001",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "AKASH SHARMA",
    rollno: "22UCSE4002",
    password: "Akash@4002",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "AMRISH KANWAT",
    rollno: "22UCSE4003",
    password: "Amrish@4003",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "ANIKET SINGH",
    rollno: "22UCSE4004",
    password: "Aniket@4004",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "ARPIT SINGHAL",
    rollno: "22UCSE4006",
    password: "Arpit@4006",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "ASHUTOSH SHARMA",
    rollno: "22UCSE4007",
    password: "Ashutosh@4007",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "ATIKSHA SHARMA",
    rollno: "22UCSE4008",
    password: "Atiksha@4008",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "BHARAT AGRAWAL",
    rollno: "22UCSE4009",
    password: "Bharat@4009",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "BHARAT JANGID",
    rollno: "22UCSE4010",
    password: "Bharat@4010",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "BHASKAR KATARA",
    rollno: "22UCSE4011",
    password: "Bhaskar@4011",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "DEEPALI SHARMA",
    rollno: "22UCSE4012",
    password: "Deepali@4012",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "DEVIN SHANESHA",
    rollno: "22UCSE4013",
    password: "Devin@4013",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "DILIP JEENGAR",
    rollno: "22UCSE4014",
    password: "Dilip@4014",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "DIPTI POONIA",
    rollno: "22UCSE4015",
    password: "Dipti@4015",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "HIMANI CHAWLA",
    rollno: "22UCSE4016",
    password: "Himani@4016",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "KAMLESH KUMAR SAINI",
    rollno: "22UCSE4017",
    password: "Kamlesh@4017",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "KAMLESH YADAV",
    rollno: "22UCSE4018",
    password: "kamlesh@4018",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "KHUSH PUROHIT",
    rollno: "22UCSE4019",
    password: "Khush@4019",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "KUMKUM SHARMA",
    rollno: "22UCSE4020",
    password: "Kumkum@4020",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "KUNAL TAMBI",
    rollno: "22UCSE4021",
    password: "Kunal@4021",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "KUNWARDEEP SINGH",
    rollno: "22UCSE4022",
    password: "Kunwardeep@4022",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "LAKSHITA DAVE",
    rollno: "22UCSE4023",
    password: "Lakshita@4023",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "MOHIT KUMAR JINDAL",
    rollno: "22UCSE4024",
    password: "Mohit@4024",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "MUSKAAN AGARWAL",
    rollno: "22UCSE4025",
    password: "Muskaan@4025",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "NARPAT KUMAR",
    rollno: "22UCSE4026",
    password: "Narpat@4026",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "PRAKHAR JAIN",
    rollno: "22UCSE4027",
    password: "Prakhar@4027",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "PRIYA GARG",
    rollno: "22UCSE4028",
    password: "Priya@4028",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "RAHUL SINGH",
    rollno: "22UCSE4029",
    password: "Rahul@4029",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "SACHIN BARUPAL",
    rollno: "22UCSE4030",
    password: "Sachin@4030",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "SOHAN LAL PRAJAPAT",
    rollno: "22UCSE4031",
    password: "Sohan@4031",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "SUMAN MEENA",
    rollno: "22UCSE4032",
    password: "Suman@4032",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "SWEETY",
    rollno: "22UCSE4033",
    password: "Sweety@4033",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "TEJASWANI BHARDWAJ",
    rollno: "22UCSE4034",
    password: "Tejaswani@4034",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "VANDANA SAINI",
    rollno: "22UCSE4035",
    password: "Vandana@4035",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "VANSH SHARMA",
    rollno: "22UCSE4036",
    password: "Vansh@4036",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "VARDA RAM",
    rollno: "22UCSE4037",
    password: "Varda@4037",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "VARDAN SHARMA",
    rollno: "22UCSE4038",
    password: "Vardan@4038",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "VINAY GUPTA",
    rollno: "22UCSE4039",
    password: "Vinay@4039",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
  {
    name: "VISHAL KHATRI",
    rollno: "22UCSE4040",
    password: "Vishal@4040",
    semester: "7th",
    branch: "CSE",
    year: 4,
  },
];
const TeacherData = [
  {
    name: "Abhishek Gour",
    teacherId: "1001",
    password: "Abhishek@1001",
    department: "Computer Science",
  },
  {
    name: "Anil Gupta",
    teacherId: "1002",
    password: "Anil@1002",
    department: "Computer Science",
  },
  {
    name: "N.C Barwar",
    teacherId: "1003",
    password: "NC@1003",
    department: "Computer Science",
  },
  {
    name: "Simran Choudary",
    teacherId: "1004",
    password: "Simran@1004",
    department: "Computer Science",
  },
];

module.exports = {data, TeacherData}
